### ISSUE TITLE
ONOS-Umbrella cannot push data to more than one Atomix RaftStore

### ISSUE THREAD

**Issue by kirazero17** [atomix/atomix#1131]
Hi everyone,

I have a project where I'd try to connect and sync the network info between two micro-ONOS cluster. What I'm trying to do is to connect the onos-umbrella components on one namespace with the raft cluster on the other.

### **Context & Conditions**

For small-scale testing, I installed two instances of onos-umbrella in two namespaces "micro-onos-1" and "micro-onos-2" in the same Azure AKS clusters with Cilium CNI and an Atomix controller instance installed in the "kube-system" namespace. I've only modified the storageprofile.yaml for onos-topo to so it can connect to the raft cluster in the other namespace (and I believe the same can be applied for other components that uses raft consensus store) as below:

```yaml
apiVersion: atomix.io/v3beta4
kind: StorageProfile
metadata:
  name: onos-topo
  namespace: micro-onos-1
  labels:
    name: onos-topo
    chart: "onos-topo-1.5.1"
    release: "onos-umbrella"
    heritage: "Helm"
spec:
  routes:
    - store:
        name: onos-topo-consensus
        namespace: micro-onos-1
      rules:
        - names:
          - '*'
        - apiVersion: v1
          config:
            cache:
              enabled: true
          kind: Map
    - store:
        name: onos-topo-consensus
        namespace: micro-onos-2
      rules:
        - names:
          - '*'
        - apiVersion: v1
          config:
            cache:
              enabled: true
          kind: Map
```

(The same was done for the one on the second cluster)

I also installed Cilium Hubble for service observation, and it shows the connection between the topo services and the consensus services between the two clusters (as the picture below)
![image](https://github.com/atomix/atomix/assets/84077194/4577193d-352a-4902-98a8-c57679977bde)

### **Problem**

Yet, when I tried to add a device to the topology through topo-discovery command on one namespace,
```bash
onos-cli-56687f8b49-lbbsx:~$ onos discovery add switch sw1 --gnmi-endpoint devicesim-1:5150 --service-address onos-umbrella-topo-discovery:5150
onos-cli-56687f8b49-lbbsx (cluster 1):~$ onos topo get entity
Entity ID                          Kind ID       Labels   Aspects
gnmi:onos-config-fdf85fddd-mxjsb   onos-config   <None>   onos.topo.Lease
sw1                                switch        <None>   onos.topo.P4RuntimeServer,onos.topo.StratumAgents,onos.topo.gNMIServer
```
it didn't appear on the other namespace. (no sw1)
```bash
onos-cli-56687f8b49-6qx25 (cluster 2):~$ onos topo get entity
Entity ID                          Kind ID       Labels   Aspects
gnmi:onos-config-fdf85fddd-pwl8m   onos-config   <None>   onos.topo.Lease
```

### **Some attempts at revealing the problem**

I then tried to isolate the problem by only deploying one instance of ONOS-Umbrella, with the consensus cluster being deployed on a different namespace from ONOS, in two ways:

**1. RaftStore deployed on the same namespace as ONOS-Umbrella**

![image](https://github.com/atomix/atomix/assets/84077194/7ef070a7-75cd-411e-9d6e-af43510bdada)

Here's the CRDs YAML for onos-topo's RaftCluster, RaftStore, and StorageProfile:

```yaml
apiVersion: raft.atomix.io/v1beta3
kind: RaftCluster
metadata:
  name: onos-umbrella-consensus
  namespace: micro-onos-data
  labels:
    name: onos-umbrella-consensus
    chart: "onos-umbrella-1.3.32"
    release: "onos-umbrella"
    heritage: "Helm"
spec:
  replicas: 5
  securityContext:
    runAsUser: 0
  persistence:
    accessModes:
    - ReadWriteOnce
    size: 8Gi
  logging:
    encoding: console
    rootLevel: debug
    loggers:
      - name: github.com/atomix/atomix/runtime/pkg/utils/grpc/interceptors
        level: debug
---
apiVersion: raft.atomix.io/v1beta3
kind: RaftStore
metadata:
  name: onos-topo-consensus
  namespace: micro-onos
  labels:
    name: onos-topo-consensus
    chart: "onos-topo-1.5.1"
    release: "onos-umbrella"
    heritage: "Helm"
spec:
  cluster:
    name: onos-umbrella-consensus
    namespace: micro-onos-data
  partitions: 10
---
apiVersion: atomix.io/v3beta4
kind: StorageProfile
metadata:
  name: onos-topo
  namespace: micro-onos
  labels:
    name: onos-topo
    chart: "onos-topo-1.5.1"
    release: "onos-umbrella"
    heritage: "Helm"
spec:
  routes:
    - store:
        name: onos-topo-consensus
        namespace: micro-onos
      rules:
        - names:
          - '*'
        - apiVersion: v1
          config:
            cache:
              enabled: true
          kind: Map
```
_Identical CRDs are defined and applied for onos-config, device-provisioner, and fabric-underlay._

In this case, the services (topo, config, device-provisioner, fabric-underlay) cannot even make a service connection to the 
 RaftClusters, and the Hubble topology show no link between them.

**2. RaftStore deployed on the same namespace as RaftCluster (similar to the two-namespace deployment)**

![image](https://github.com/atomix/atomix/assets/84077194/344a4f46-1ee9-4951-bed8-8122aecb04fd)

Here's the CRDs YAML for onos-topo's  RaftCluster, RaftStore, and StorageProfile:
```yaml
apiVersion: raft.atomix.io/v1beta3
kind: RaftCluster
metadata:
  name: onos-umbrella-consensus
  namespace: micro-onos-data
  labels:
    name: onos-umbrella-consensus
    chart: "onos-umbrella-1.3.32"
    release: "onos-umbrella"
    heritage: "Helm"
spec:
  replicas: 5
  securityContext:
    runAsUser: 0
  persistence:
    accessModes:
    - ReadWriteOnce
    size: 8Gi
  logging:
    encoding: console
    rootLevel: debug
    loggers:
      - name: github.com/atomix/atomix/runtime/pkg/utils/grpc/interceptors
        level: debug
---
apiVersion: raft.atomix.io/v1beta3
kind: RaftStore
metadata:
  name: onos-topo-consensus
  namespace: micro-onos-data
  labels:
    name: onos-topo-consensus
    chart: "onos-topo-1.5.1"
    release: "onos-umbrella"
    heritage: "Helm"
spec:
  cluster:
    name: onos-umbrella-consensus
    namespace: micro-onos-data
  partitions: 10
---
apiVersion: atomix.io/v3beta4
kind: StorageProfile
metadata:
  name: onos-topo
  namespace: micro-onos
  labels:
    name: onos-topo
    chart: "onos-topo-1.5.1"
    release: "onos-umbrella"
    heritage: "Helm"
spec:
  routes:
    - store:
        name: onos-topo-consensus
        namespace: micro-onos-data
      rules:
        - names:
          - '*'
        - apiVersion: v1
          config:
            cache:
              enabled: true
          kind: Map
```
_Identical CRDs are defined and applied for onos-config, device-provisioner, and fabric-underlay._

In this case, the services (topo, config, device-provisioner, fabric-underlay) can make a service connection to the RaftClusters, and the Hubble topology shows the link. However, onos-config is not automatically added into the topology, even though I can still add the devices with topo-discovery into onos-topo.

I don't know if micro-ONOS supports multiple raft store for components like onos-topo, or where did I do wrong.
